package com.opscontrolplane.workflows;

public enum WorkflowType {
    RETRY_KAFKA_BATCH,
    APPROVE_CONFIG_ROLLOUT,
    RESTART_EDGE_GATEWAY,
    VALIDATE_METERING_PIPELINE,
    INCIDENT_REVIEW,
    SCALE_K8S_DEPLOYMENT,
    VALIDATE_SOAP_ADAPTER_RECOVERY,
    RESTART_EMS_BRIDGE
}
